SELECT MigrationId FROM [__EFMigrationsHistory] ORDER BY MigrationId;
SELECT COLUMN_NAME, IS_NULLABLE, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Messages' AND COLUMN_NAME='SenderId';
SELECT COLUMN_NAME, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DoctorPreferences';
