using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackendAPI.Source.Models.Entities;
using BackendAPI.Source.Models.Enums;
using System.ComponentModel.DataAnnotations;
using BackendAPI.Source.Models.Interface;

namespace BackendAPI.Source.Models.Dto
{
    public record DoctorDto
    {
        public required Guid DoctorId { get; set; }
        public required Guid UserId { get; set; }

        // from UserModel
        public required string FirstName { get; set; }
        public required string LastName { get; set; }
        public required string Email { get; set; }
        public bool IsEmailVerified { get; set; } = false;

        public required string Phone { get; set; }
        public required Gender Gender { get; set; }
        public required DateOnly DateOfBirth { get; set; }
        public required string Address { get; set; }
        public string? ProfilePicture { get; set; }


        // from DoctorModel
        public required string Qualifications { get; set; }
        public required List<string> SpecialtyModel { get; set; }
        public required string Biography { get; set; }
        public DoctorStatus DoctorStatus { get; set; } = DoctorStatus.Active;
    }


    // DTO for creating a doctor, it does not include DoctorId and UserId because they will be generated by the system
    public record CreateDoctorDto
    {
        // from UserModel
        [Required]
        public required UserModel User { get; init; }

        [Required]
        public required FileModel Cv { get; init; }

        public DoctorStatus DoctorStatus { get; init; } = DoctorStatus.Active;
        [Required]
        public required string Qualifications { get; init; }

        [Required]
        public required string Biography { get; init; }

        [Required]
        public required decimal OnlineAppointmentFee { get; init; }

        [Required]
        public required decimal InPersonAppointmentFee { get; init; }

        [Required]
        public required List<CreateEducationDto> Educations { get; set; }
        public required List<CreateExperienceDto> Experiences { get; set; }


    }

    //Dto for
    public record EditDoctorDto
    (
        Guid UserId,
        string? Biography,
        string? Qualifications,
        string? DoctorStatus,
        List<string>? SpecialtyModel

    );

    public record DoctorSchedule(AppointmentTimeRange TimeRange, bool IsFree);

    public record UpdateDoctorProfileDto(
       Guid UserId,
       List<string>? Specialties = null,
       string? Qualifications = null,
       string? Biography = null,
       List<DoctorAvailabilityDto>? Availabilities = null,
       string? DoctorStatus = null,
       List<UpdateEducationDto>? Educations = null,
       List<UpdateExperienceDto>? Experiences = null);

    public record DoctorSchedules(Dictionary<DateOnly, List<DoctorSchedule>> Data);

    // DTO for approving a doctor
    public record ApproveDoctorDto
    {
        public Guid DoctorId { get; set; }
        public string? AdminNotes { get; set; }
    }

    // DTO for rejecting a doctor
    public record RejectDoctorDto
    {
        public Guid DoctorId { get; set; }
        public required string Reason { get; set; }
    }

    // DTO for doctor approval status response
    public record DoctorApprovalResponse
    {
        public Guid DoctorId { get; set; }
        public bool IsVerified { get; set; }
        public DoctorStatus DoctorStatus { get; set; }
        public string Message { get; set; } = string.Empty;
    }

    // DTO for pending doctors list
    public record PendingDoctorDto
    {
        public Guid DoctorId { get; set; }
        public Guid UserId { get; set; }
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Qualifications { get; set; } = string.Empty;
        public string Biography { get; set; } = string.Empty;
        public List<string> Specialties { get; set; } = new();
        public DateTime RegisteredAt { get; set; }
        public string? CvUrl { get; set; }
    }

}