using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackendAPI.Source.Models.Entities;
using BackendAPI.Source.Models.Enums;
using System.ComponentModel.DataAnnotations;
using BackendAPI.Source.Models.Interface;

namespace BackendAPI.Source.Models.Dto
{
    public record DoctorDto
    {
        public required Guid DoctorId { get; set; }
        public required Guid UserId { get; set; }

        // from UserModel
        public required string FirstName { get; set; }
        public required string LastName { get; set; }
        public required string Email { get; set; }
        public bool IsEmailVerified { get; set; } = false;

        public required string Phone { get; set; }
        public required Gender Gender { get; set; }
        public required DateOnly DateOfBirth { get; set; }
        public required string Address { get; set; }
        public string? ProfilePicture { get; set; }


        // from DoctorModel
        public required string Qualifications { get; set; }
        public required List<string> SpecialtyModel { get; set; }
        public required string Biography { get; set; }
        public DoctorStatus DoctorStatus { get; set; } = DoctorStatus.Active;
    }


    // DTO for creating a doctor, it does not include DoctorId and UserId because they will be generated by the system
    public record CreateDoctorDto
    {
        // from UserModel
        [Required]
        public required UserModel User { get; init; }

        [Required]
        public required FileModel Cv { get; init; }

        [Required]
        public required string Qualifications { get; init; }

        [Required]
        public required string Biography { get; init; }

        [Required]
        public required decimal OnlineAppointmentFee { get; init; }

        [Required]
        public required decimal InPersonAppointmentFee { get; init; }



        public DoctorStatus DoctorStatus { get; init; } = DoctorStatus.Active;
    }

    //Dto for
    public record EditDoctorDto
    (
        Guid UserId,
        string? Biography,
        string? Qualifications,
        string? DoctorStatus,
        List<string>? SpecialtyModel

    );

    public record DoctorSchedule(AppointmentTimeRange TimeRange, bool IsFree);

    public record DoctorSchedules(Dictionary<DateOnly, List<DoctorSchedule>> Data);

}