using System;
using System.ComponentModel.DataAnnotations;

namespace BackendAPI.Source.Models.Entities
{
    /// <summary>
    /// Represents an official medical prescription generated by a Doctor within a telemedicine conversation.
    /// </summary>
    public class PrescriptionModel : BaseEntity
    {
        [Key]
        public Guid PrescriptionId { get; set; } = Guid.NewGuid();

        // The specific message node this prescription belongs to
        [Required]
        public Guid MessageId { get; set; }

        [Required]
        public Guid DoctorId { get; set; }

        [Required]
        public Guid PatientId { get; set; }

        [Required]
        public required string Medication { get; set; }

        [Required]
        public required string Dosage { get; set; }

        [Required]
        public required string Frequency { get; set; }

        [Required]
        public required string Duration { get; set; }

        // Navigation Properties
        public virtual Message? Message { get; set; }
        public virtual DoctorModel? Doctor { get; set; }
        public virtual PatientModel? Patient { get; set; }
    }
}
